### ISSUE TITLE
Skip Alignment

### ISSUE THREAD

**Issue by beausmith94** [wpwupingwp/BarcodeFinder#1]
How can I skip the alignment step?

I would like to download my query, apply -unique longest, but NOT align.

I understand the skip_primer, but I also want to -skip_align. -no_divide forces -unique not to execute. 

I want to compare alignment characteristics across programs like CLC and BarcodeFinder. 

This is an incredible tool by the way!

-Beau

**Comment by wpwupingwp** [comment]
hi，
you can use gb2fasta module only,
by
```
python3 BarcodeFinder.gb2fasta [your options]
```

**Comment by beausmith94** [comment]
Thank you!
